services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - 5678:5678
    environment:
      - TZ=Europe/Madrid
      - N8N_HOST=n8n.homelab
      - N8N_PROTOCOL=http
      - N8N_SECURE_COOKIE=false
      - WEBHOOK_URL=http://n8n.homelab/
    volumes:
      - /path/to/data:/home/node/.n8n
networks: {}

