services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    network_mode: host
    volumes:
      - /path/to/work:/opt/adguardhome/work
      - /path/to/conf:/opt/adguardhome/conf
    environment:
      - TZ=Europe/Madrid
networks: null

