services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest-ultra-lite
    container_name: stirling-pdf
    ports:
      - 8008:8080
    volumes:
      - /path/to/data:/configs
    restart: unless-stopped
